### ISSUE TITLE
GameUI2 menu doesn't load without a background map

### ISSUE THREAD

**Issue by GamerDude27** [NicolasDe/project-9#2]
Hello,

I'm trying to use a background image instead of a background map.
But when doing so the menu doesn't appear, BUT, if I load up a map through the console and disconnect from it taking me back to the main menu I can see the menu again.
Why does this happen and how can I fix it?

**Comment by NicolasDe** [comment]
Well for starters, I'd return sign with my license on your fork ;)

**Comment by GamerDude27** [comment]
Excuse me, what? If you're talking about crediting you then that's already done

**Comment by GamerDude27** [comment]
Any help is appreciated

**Comment by NicolasDe** [comment]
Fixed the issue.
